const LOGIN = {
  REQUEST: 'LOGIN_REQUEST',
  SUCCESS: 'LOGIN_SUCCESS',
  FAILURE: 'LOGIN_FAILURE',
};
const LOGOUT = { SUCCESS: 'LOGOUT_SUCCESS' };

const GET_INTERNSHIPS = {
  REQUEST: 'GET_INTERNSHIPS_REQUEST',
  SUCCESS: 'GET_INTERNSHIPS_SUCCESS',
  FAILURE: 'GET_INTERNSHIPS_FAILURE',
};

export { LOGIN, LOGOUT, GET_INTERNSHIPS };
