const LOGIN = {
  REQUEST: 'LOGIN_REQUEST',
  SUCCESS: 'LOGIN_SUCCESS',
  FAILURE: 'LOGIN_FAILURE',
};
const LOGOUT = { SUCCESS: 'LOGOUT_SUCCESS' };

const GETCANDIDATELIST = {
  REQUEST: 'GETCANDIDATELIST_REQUEST',
  SUCCESS: 'GETCANDIDATELIST_SUCCESS',
  FAILURE: 'GETCANDIDATELIST_FAILURE',
};

export { LOGIN, LOGOUT, GETCANDIDATELIST };
